{{- if .Values.k8sJenkinsMgmt.loadbalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8sJenkinsMgmt.ingress.deploymentName }}-lb
  namespace: {{ .Values.k8sJenkinsMgmt.ingress.namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  {{- if .Values.k8sJenkinsMgmt.loadbalancer.annotations.enabled}}
  annotations:
  {{- if .Values.k8sJenkinsMgmt.loadbalancer.annotations.external_dns_hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.k8sJenkinsMgmt.loadbalancer.annotations.external_dns_hostname }}
  {{- end }}
  {{- if .Values.k8sJenkinsMgmt.loadbalancer.annotations.external_dns_ttl }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.k8sJenkinsMgmt.loadbalancer.annotations.external_dns_ttl }}
  {{- end }}
  {{- end }}

spec:
  # externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{ .Values.k8sJenkinsMgmt.ingress.loadbalancerIp }}
  ports:
    - port: {{ .Values.k8sJenkinsMgmt.loadbalancer.ports.http.port }}
      name: http
      targetPort: {{ .Values.k8sJenkinsMgmt.loadbalancer.ports.http.targetPort }}
    - port: {{ .Values.k8sJenkinsMgmt.loadbalancer.ports.https.port }}
      name: https
      targetPort: {{ .Values.k8sJenkinsMgmt.loadbalancer.ports.https.targetPort }}
  selector:
    # Selects nginx-ingress-controller pods
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
{{- end }}
